---
title: "Homework_5"
author: "Molly Hischke"
date: "11/6/2019"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, warning = FALSE, 
                      message = FALSE, errors = FALSE)
```

## HOMEWORK QUESTIONS:
(1) What kind of information should be included in the README.md?
(2) I rigged the dates to work in the graph. See line 45/46. Is this okay? Other ways of doing?
(3) For geom_smooth, does this line need to be thicker? I can't get size to work. See line 72

## Read in Homicide Data

```{r Loading in Homicide Data}
library(readr)
library(dplyr)
homicides <- read_csv("../data/homicide-data.csv")

homicides <- homicides %>% 
  mutate(city_name = paste(city, state, sep = ", "))

```

## Cleaning the data

```{r Cleaning the data}
library(tidyr)
library(forcats)
library(lubridate)


baltimore_homicides <- homicides %>% 
  filter(city_name == "Baltimore, MD") %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  mutate(month_data = month(reported_date),
         year_data = year(reported_date)) %>% 
  group_by(month_data, year_data) %>% 
  summarize(total = n()) %>% 
  mutate(date = paste(month_data, year_data, sep = "-1-"), ## QUESTION 2
         date = mdy(date)) %>% 
  mutate(colder_vs_warmer_months = month(month_data) == "11" |
                                   month(month_data) == "12" |
                                   month(month_data) == "1"  |
                                   month(month_data) == "2"  |
                                   month(month_data) == "3"  |
                                   month(month_data) == "4",
         colder_vs_warmer_months = factor(colder_vs_warmer_months, 
                                          levels = c(FALSE, TRUE),
                                          labels = c("Summer", "Winter")))
         

```

## Homicides in Baltimore, MD Graph

```{r ggplot, fig.height = 2, fig.width = 8}
library(ggplot2)

baltimore_homicides %>% 
  ggplot(aes(x = date, y = total)) +
  geom_col(aes(fill = colder_vs_warmer_months)) +
  geom_vline(xintercept = ymd("2015-4-1"), color = "red", linetype = 2, 
             size = 1.3) +
  geom_text(aes(x = ymd("2015-4-1"), label = "Arrest of \nFreddie Gray", 
                y = 40), colour = "gray80", hjust = "right") +
  geom_smooth(span = 0.1 , se = FALSE) + ## QUESTION 3
  labs(x = "Date",
       y = "Monthly homicides",
       title = "Homicides in Baltimore, MD",
       fill = "") +
  scale_fill_manual(values = c("gray80", "lightblue")) + 
  theme_dark() +
  theme(legend.position = "bottom") 

```

